---
title: "Democratic Presidential Fundraising as of 01 July 2019"
output: html_notebook
---


#### Commands
**Run**: place cursor inside code chunk, **Ctrl + Shift + Enter**. 

**New chunk: Ctrl + alt + i**.

**Preview HTML file: Ctrl + Shift + K**.

Unlike *Knit*, *Preview* does not run any code chunks.
Instead, the output of the chunk when it was last run is displayed.

### Installation & Setup
```{r setup}
# INSTALLING PACKAGES:
# install.packages("PackageName")

library(dplyr)
library(ggplot2)
library(readr)
```

#### Import Data
```{r data}
# Import data from CSV as tibble (relative path)
data <- read_csv(file = '2019-07-01_dem-POTUS.csv', col_names = TRUE)

# look at structure of data
str(data)

# view data in separate tab
View(data)

```


#### Cleaning Data
I'm including only the candidates who were in the first debate, and adding Bullock.
```{r clean}
# Save column names to columns
columns <- colnames(data)

# Keep only columns needed for analysis


# create a list of the 20 candidates who qualified
# for the first democratic primary debate

candidates <- c("Bennett", "Biden",
                "Booker", "Bullock",
                "Buttigieg", "Castro",
                "de Blasio", "Delaney",
                "Gabbard", "Gillibrand",
                "Harris", "Inslee",
                "Klobuchar", "Moulton",
                "O'Rourke", "Ryan",
                "Sanders", "Warren",
                "Williamson", "Yang")

# loop through names to retain only rows in candidates variable


```

